apiVersion: v1
kind: Secret
metadata:
  name: panel-admin-secrets
  namespace: airflow
type: Opaque
stringData:
  # --- MinIO ---
  MINIO_ENDPOINT: "http://minio.mon-namespace.svc.cluster.local:80"
  MINIO_ACCESS_KEY: "<access_key>"
  MINIO_SECRET_KEY: "<secret_key>"
  BUCKET_STAGING: "staging"
  BUCKET_BRONZE: "bronze"
  BUCKET_SILVER: "silver"
  BUCKET_GOLD: "gold"

  # --- PostgreSQL ---
  PG_HOST: "postgres-service.postgres.svc.cluster.local"
  PG_PORT: "5432"
  PG_DB: "datalab_db"
  PG_USER: "datalab"
  PG_PASSWORD: "<mot_de_passe>"

  # --- Pipeline ---
  MIN_OBS_IMPUTATION: "5"
